site_name: The Recipesitory
site_url: https://food.raymeredith.com/
repo_name: RaydioAM/recipesitory
repo_url: https://github.com/RaydioAM/recipesitory

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/food
    repo: fontawesome/brands/github

markdown_extensions:
  - tables
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.betterem
  - pymdownx.superfences

# Page tree
nav:
  - Home: index.md
  - Breakfast:
    - Gordon Ramsay Scrambled Eggs: recipes/scrambled-eggs.md
  - Appetizers:
    - Cranberry Brie Bites: recipes/cranberry-brie-bites.md
    - Test failing build:
  - Dinner:
    - Beef Wellington: recipes/beef-wellington.md
    - French Onion Soup: recipes/french-onion-soup.md
    - Shepherd's Pie: recipes/shepherds-pie.md
    - Spicy Sausage and Rice: recipes/spicy-sausage-rice.md
  - Editing Guide: editing-guide.md
